name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: production
    environment:
      name: Production
      url: https://fiat.pages.dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - run: |
          cargo install wasm-server-runner
          cargo install wasm-bindgen-cli
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-name main --out-dir dist --target web ./target/wasm32-unknown-unknown/release/let-it-be-done.wasm
          cp -a ./assets ./dist
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=fiat dist
